# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

target 'reactmaps' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactmaps
  pod ‘yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'GoogleMaps'
end
